version: '3.8'

services:
  # Fastify application container
  app:
    build: .
    container_name: fastify-app
    ports:
      - "3000:3000" # Expose Fastify port
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379 # Redis container address
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=game_events
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  # Redis container for BullMQ queue
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    volumes:
      - redis-data:/data

  # PostgreSQL container for the database
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game_events
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
